import mongoose from "mongoose";
import dotenv from "dotenv";
import User, { IUser } from "../src/models/user.model";
import { v4 as uuidv4 } from "uuid";

dotenv.config(); // Load environment variables from .env file

const createTestUserAndApiKey = async () => {
  const mongoUri = process.env.MONGO_URI;
  if (!mongoUri) {
    console.error(
      "MONGO_URI not found in .env file. Please ensure it is set. " +
        'You might need to run "yarn setup" or copy .env.example to .env and configure it.'
    );
    process.exit(1);
  }

  try {
    await mongoose.connect(mongoUri);
    console.log("Successfully connected to MongoDB.");

    const uniqueId = uuidv4().substring(0, 8);
    const userEmail = `test-manual-${uniqueId}@example.com`;
    const userPassword = `PasswordTest123!_${uniqueId}`; // Make password unique too

    let testUser: IUser | null = await User.findOne({ email: userEmail });

    if (testUser) {
      console.log(`User with email ${userEmail} already exists.`);
      if (!testUser.apiKey) {
        console.log(
          "User exists but has no API key. Attempting to generate one."
        );
        // The pre-save hook should handle API key generation if it's missing on a new save,
        // but an existing user should ideally always have one.
        // Forcibly generating if missing, though this scenario is unlikely with current model.
        testUser.apiKey = uuidv4();
        await testUser.save();
        console.log("API key generated/ensured for existing user.");
      }
    } else {
      console.log(`Creating new user with email: ${userEmail}`);
      testUser = new User({
        email: userEmail,
        password: userPassword,
        // API key will be generated by pre-save hook in user.model.ts
      });
      await testUser.save();
      console.log("New user created successfully.");
    }

    if (!testUser.apiKey) {
      console.error(
        "API key was not generated for the user. " +
          "This is unexpected. Check user.model.ts pre-save hook."
      );
      process.exit(1);
    }

    console.log("\\n--- Test User Credentials ---");
    console.log(`Email: ${testUser.email}`);
    console.log(`API Key: ${testUser.apiKey}`);
    console.log("\\nUse this API key to test the /exec and /cons endpoints:");
    console.log(`Execution Layer Example: POST /exec/${testUser.apiKey}`);
    console.log(
      `Consensus Layer Example: GET /cons/${testUser.apiKey}/eth/v1/beacon/headers`
    );
    console.log("-----------------------------");
  } catch (error) {
    console.error(
      "Error during test user creation or API key generation:",
      error
    );
    process.exitCode = 1; // Indicate an error exit
  } finally {
    if (mongoose.connection.readyState === 1) {
      // 1 means connected
      await mongoose.disconnect();
      console.log("Disconnected from MongoDB.");
    }
  }
};

createTestUserAndApiKey();
